app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('product', 'Views\ProductController');
Route::resource('component', 'Views\ComponentController');
Route::resource('package', 'Views\PackageController');
Route::resource('client', 'Views\ClientController');

Route::controller('/inv', 'InventoryController');
Route::controller('/bus', 'BusinessController');
Route::controller('/ops', 'OperationsController');

Route::controller('/misc', 'MiscellaneousController');
Route::auth();

Route::get('/home', 'HomeController@index');

Route::post('login', 'Auth\AuthController@login');
Route::get('transaction/client/{clientid}', 'OperationsController@transactionsByClient');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/main.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <style>
        table form { margin-bottom: 0; }
        form ul { margin-left: 0; list-style: none; }
        .error { color: red; font-style: italic; }
        body { padding-top: 20px; }
    </style>
</head>

<body>
    @include('sidebar')
    @yield('content')

</body>

</html>

resources/views/sidebar.blade.php
@section('sidebar')

    <div class="nav">
        <!-- Sidebar Menu -->
        <ul class="nav nav-tabs">
            <!-- Optionally, you can add icons to the links -->
            <li>{!! link_to_route("client.index", "Clientes") !!}</li>
            <li>{!! link_to_route("component.index", "Componentes") !!}</li>
            <li>{!! link_to_route("product.index", "Productos") !!}</li>
            <li>{!! link_to_route("package.index", "Paquetes") !!}</li>
        </ul><!-- /.sidebar-menu -->

    </div><!-- /.main-sidebar -->

@show