app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('product', 'Views\ProductController');
Route::resource('component', 'Views\ComponentController');
Route::resource('package', 'Views\PackageController');
Route::resource('client', 'Views\ClientController');

Route::controller('/inv', 'InventoryController');
Route::controller('/bus', 'BusinessController');
Route::controller('/ops', 'OperationsController');

Route::controller('/misc', 'MiscellaneousController');
Route::auth();

Route::get('/home', 'HomeController@index');

Route::post('login', 'Auth\AuthController@login');
Route::get('transaction/client/{clientid}', 'OperationsController@transactionsByClient');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class Client extends Model
{
    protected $fillable = ['name', 'last_name', 'business', 'phone', 'email', 'school_id'];

    public function school(){
        return $this->belongsTo('App\Models\School');
    }

    public function transactions(){
        return $this->hasMany('App\Models\Transaction');
    }
    
    static public function insert($data){

        $client = Client::create(array_filter($data, function($item){
            $client = new Client();
            return array_search($item, $client->fillable) !== false;
        }, ARRAY_FILTER_USE_KEY));

        return $client;
    }

    static public function select($id, $extra = false){
        if($id > 0)
            $clients = Client::find($id);
        else
            $clients = Client::all();

        if($extra){
            if(isset($clients[0])) {
                foreach ($clients as &$client) {
                    $client['school'] = $client->school;
                    $client['transactions'] = Transaction::select(
                        array_map(
                            function($transaction){return $transaction['id'];},
                            $client->transactions),
                        true);
                }
            } else {
                $transactionsid = array_map(
                    function($transaction){return $transaction['id'];},
                    $clients->transactions->toArray());

                $clients['school'] = $clients->school;
                $clients['transactions'] = Transaction::select(
                    $transactionsid,
                    true);
            }
        }

        return $clients;
    }

    static public function actualize($id, $data){
        $data = array_filter($data, function($item){
            $client = new Client();
            return array_search($item, $client->fillable) !== false;
        }, ARRAY_FILTER_USE_KEY);
        $client = Client::find($id);
        $client->update($data);

        return $client;
    }

    static public function remove($id){
        return Client::destroy($id);
    }
}

app/Http/Controllers/Views/ClientController.php
<?php

namespace App\Http\Controllers\Views;

use App\Http\Controllers\BusinessController;
use App\Client;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::select(-1);
        return view('clients.index', ['clients' => $clients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        (new BusinessController())->postClient($request);

        return redirect()->route('client.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $clients = Client::select($id);
        return redirect()->route('client.index', ['clients' => $clients]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);
        if (is_null($client))
        {
            return redirect()->route('client.index');
        }
        return view('clients.edit', ['client' => $client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        (new BusinessController())->putClient($request, $id);

        return redirect()->route('client.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Client::remove($id);

        return redirect()->route('client.index');
    }
}

resources/views/clients/create.blade.php
@extends('main')

@section('content')

    <h1>Crear Clientes</h1>

    {{ Form::open(array('route' => 'client.store')) }}
    <ul>

        <li>
            {{ Form::label('name', 'Nombre:') }}
            {{ Form::text('name') }}
        </li>

        <li>
            {{ Form::label('last_name', 'Apellido:') }}
            {{ Form::text('last_name') }}
        </li>

        <li>
            {{ Form::label('email', 'Correo:') }}
            {{ Form::text('email') }}
        </li>

        <li>
            {{ Form::label('phone', 'Telefono:') }}
            {{ Form::text('phone') }}
        </li>

        <li>
            {{ Form::label('business', 'Razon Social:') }}
            {{ Form::text('business') }}
        </li>

        <li>
            {{ Form::submit('Submit', array('class' => 'btn')) }}
        </li>
    </ul>
    {{ Form::close() }}

    @if ($errors->any())
        <ul>
            {{ implode('', $errors->all('<li class="error">:message</li>')) }}
        </ul>
    @endif

@stop

resources/views/clients/edit.blade.php
@extends('main')

@section('content')

    <h1>Editar Cliente</h1>

    {{ Form::model($client, ['method' => 'PUT', 'route' => ['client.update', $client->id]]) }}

    <ul>

        <li>
            {{ Form::label('name', 'Nombre:') }}
            {{ Form::text('name') }}
        </li>

        <li>
            {{ Form::label('last_name', 'Apellido:') }}
            {{ Form::text('last_name') }}
        </li>

        <li>
            {{ Form::label('email', 'Correo:') }}
            {{ Form::text('email') }}
        </li>

        <li>
            {{ Form::label('phone', 'Telefono:') }}
            {{ Form::text('phone') }}
        </li>

        <li>
            {{ Form::label('business', 'Razon Social:') }}
            {{ Form::text('business') }}
        </li>

        <li>
            {{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
            {{ link_to_route('client.show', 'Cancel', $client->id, array('class' => 'btn')) }}

        </li>
    </ul>
    {{ Form::close() }}

    @if ($errors->any())
        <ul>
            {{ implode('', $errors->all('<li class="error">:message</li>')) }}
        </ul>
    @endif

@stop

resources/views/clients/index.blade.php
@extends('main')

@section('content')

    <h1>Clientes</h1>

    <p>{{ link_to_route('client.create', 'Agregar nuevo cliente') }}</p>
    @if ($clients->count())
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Correo</th>
                <th>Telefono</th>
                <th>Razon Social</th>
            </tr>
            </thead>

            <tbody>

            @foreach ($clients as $client)
                <tr>
                    <td>{{ $client['name'] }}</td>
                    <td>{{ $client['last_name'] }}</td>
                    <td>{{ $client['email'] }}</td>
                    <td>{{ $client['phone'] }}</td>
                    <td>{{ $client['business'] }}</td>
                    <td>{{ link_to_route('client.edit', 'Editar', [$client['id']], array('class' => 'btn btn-info')) }}</td>
                    <td>
                        {{ Form::open(['method' => 'DELETE', 'route' => ['client.destroy', $client['id']]]) }}
                        {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
                </tr>
            @endforeach

            </tbody>

        </table>
    @else
        No hay clientes
    @endif

@stop