app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('product', 'Views\ProductController');
Route::resource('component', 'Views\ComponentController');
Route::resource('package', 'Views\PackageController');
Route::resource('client', 'Views\ClientController');

Route::controller('/inv', 'InventoryController');
Route::controller('/bus', 'BusinessController');
Route::controller('/ops', 'OperationsController');

Route::controller('/misc', 'MiscellaneousController');
Route::auth();

Route::get('/home', 'HomeController@index');

Route::post('login', 'Auth\AuthController@login');
Route::get('transaction/client/{clientid}', 'OperationsController@transactionsByClient');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use App\Component;

class Product extends Model
{
    // Columns
    protected $fillable = ['code', 'price', 'discount', 'description', 'image', 'category_id'];

    public function isFillableItem($item){
        $product = new Product();
        return array_search($item, $product->fillable) != false;
    }

    public function category(){
        return $this->belongsTo('App\Models\Category');
    }

    public function components(){
        return $this->belongsToMany('App\Models\Component', 'product_component')->withPivot('amount');
    }

    public function packages(){
        return $this->belongsToMany('App\Models\Package', 'package_product')->withPivot('amount');
    }

    public function quotes(){
        return $this->belongsToMany('App\Models\Quote', 'quote_product')->withPivot('amount');
    }

    public function sales(){
        return $this->belongsToMany('App\Models\Sale', 'sale_product')->withPivot('amount');
    }
    
    static public function insert($data, $items = []){
        $product = Product::create(array_filter($data, function($item){
            $product = new Product();
            return array_search($item, $product->fillable) !== false;
        }, ARRAY_FILTER_USE_KEY));

        foreach ($items as $item) {
            $component = Component::find($item['id']);
            $product->components()->save($component, ['amount' => $item['amount']]);
        }

        return $product;
    }

    static public function select($id, $extra = false){
        if($id > 0)
            $products = Product::find($id);
        else
            $products = Product::all();

        if($extra){
            if(isset($products[0])) {
                foreach ($products as &$product) {
                    $product['components'] = $product->components;
                    $product['packages'] = $product->packages;
                    $product['category'] = $product->category;
                }
            }else{
                $products['components'] = $products->components;
                $products['packages'] = $products->packages;
                $products['category'] = $products->category;
            }
        }

        return $products;
    }

    static public function actualize($id, $data, $items){
        $data = array_filter($data, function($item){
            $product = new Product();
            return array_search($item, $product->fillable) !== false;
        }, ARRAY_FILTER_USE_KEY);
        $product = Product::find($id);
        $product->update($data);

        $product->components()->detach();
        foreach ($items as $item) {
            $component = Component::find($item['id']);
            $product->components()->save($component, ['amount' => $item['amount']]);
        }
        
        return $product;
    }

    static public function remove($id){
        $product = Product::find($id);
        $product->components()->detach();
        $product->packages()->detach();
        return Product::destroy($id);
    }
    
    static public function totalPrice($products){
        $total = 0;
        foreach ($products as $product) {
            $total += $product['price'];
        }
        return $total;
    }
}

app/Http/Controllers/Views/ProductController.php
<?php

namespace App\Http\Controllers\Views;

use App\Http\Controllers\InventoryController;
use App\Product;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::select(-1);
        return view('products.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        (new InventoryController())->postProduct($request);

        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $products = Product::select($id);
        return redirect()->route('product.index', ['products' => $products]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        if (is_null($product))
        {
            return redirect()->route('products.index');
        }
        return view('products.edit', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        (new InventoryController())->putProduct($request, $id);

        return redirect()->route('product.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::remove($id);

        return redirect()->route('product.index');
    }
}

resources/views/products/create.blade.php
@extends('main')

@section('content')

    <h1>Create Product</h1>

    {{ Form::open(array('route' => 'product.store')) }}
    <ul>

        <li>
            {{ Form::label('code', 'Clave:') }}
            {{ Form::text('code') }}
        </li>

        <li>
            {{ Form::label('description', 'Descripcion:') }}
            {{ Form::text('description') }}
        </li>

        <li>
            {{ Form::label('price', 'Precio:') }}
            {{ Form::text('price') }}
        </li>

        <li>
            {{ Form::submit('Submit', array('class' => 'btn')) }}
        </li>
    </ul>
    {{ Form::close() }}

    @if ($errors->any())
        <ul>
            {{ implode('', $errors->all('<li class="error">:message</li>')) }}
        </ul>
    @endif

@stop

resources/views/products/edit.blade.php
@extends('main')

@section('content')

    <h1>Edit Product</h1>

    {{ Form::model($product, ['method' => 'PUT', 'route' => ['product.update', $product->id]]) }}

    <ul>

        <li>
            {{ Form::label('code', 'Clave:') }}
            {{ Form::text('code') }}
        </li>

        <li>
            {{ Form::label('description', 'Descripcion:') }}
            {{ Form::text('description') }}
        </li>

        <li>
            {{ Form::label('price', 'Precio:') }}
            {{ Form::text('price') }}
        </li>

        <li>
            {{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
            {{ link_to_route('product.show', 'Cancel', $product->id, array('class' => 'btn')) }}

        </li>
    </ul>
    {{ Form::close() }}

    @if ($errors->any())
        <ul>
            {{ implode('', $errors->all('<li class="error">:message</li>')) }}
        </ul>
    @endif

@stop

resources/views/products/index.blade.php
@extends('main')

@section('content')

    <h1>Products</h1>

    <p>{{ link_to_route('product.create', 'Add new product') }}</p>
    @if ($products->count())
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Clave</th>
                <th>Descripcion</th>
                <th>Precio</th>
                <th>Imagen</th>
            </tr>
            </thead>

            <tbody>

            @foreach ($products as $product)
                <tr>
                    <td>{{ $product['code'] }}</td>
                    <td>{{ $product['description'] }}</td>
                    <td>{{ $product['price'] }}</td>
                    <td>{{ $product['image'] }}</td>
                    <td>{{ link_to_route('product.edit', 'Edit', [$product['id']], array('class' => 'btn btn-info')) }}</td>
                    <td>
                        {{ Form::open(['method' => 'DELETE', 'route' => ['product.destroy', $product['id']]]) }}
                        {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
                </tr>
            @endforeach

            </tbody>

        </table>
    @else
        There are no users
    @endif

@stop